apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-stag
spec:
  acme:
       # The ACME server URL
  server: https://acme-v02.api.letsencrypt.org/directory
       # Email address used for ACME registration
  email: admin@simplek8s.com 
       # Name of a secret used to store the ACME account private key
  privateKeySecretRef:
    name: letsencrypt-stag
       # Enable the HTTP-01 challenge provider
  solvers:
    - http01:
        ingress:
          class: nginx
